### ISSUE TITLE
Error with different image resolution

### ISSUE THREAD

**Issue by steven20605** [codebox/image_augmentor#5] opened 2018-06-04 17:11 UTC
I got this error for images that are 2880*1920 but works fine with 2304*1536

<img width="434" alt="00" src="https://user-images.githubusercontent.com/24932334/40931327-4d9a9f8c-685d-11e8-9426-d3749476c72e.PNG">

**Comment by codebox** [comment] 2019-10-08 12:52
Can you upload an example image that gives this error?

**Comment by codebox** [comment] 2019-10-23 13:46
closing - cannot reproduce, no example image provided

**Closed by codebox** 2019-10-23 13:46 UTC
